auto: true
markdown: rdiscount
permalink: /:title.html

safe: true
lsi: false
pygments: true

site: 
    title: "Integralist"
    url: "http://integralist.co.uk/"

googleAnalytics: 
    id: "UA-33159515-1"

feedburner:
  id: "Integralist"